apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: fargate-cluster
  region: ap-southeast-1
fargateProfiles:
  - name: fargate-default-profile
    selectors:
     - namespace: kube-system
     - namespace: default
